// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnubfcgoaftnrvfoxxck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudWJmY2dvYWZ0bnJ2Zm94eGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjg1MDcsImV4cCI6MjA2NjgwNDUwN30.tHj2qwIkZzUJIQ4kPYdGxTHQEA8Vf1F-ivPd0Iz00cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});